### PR TITLE
Added usage of registered sqs client when available

### PR DESCRIPTION
**Pull request by tasadar2**

### CODE REVIEW

**Review by JustinMoss — APPROVED** [review]
👍

**Review by bfriesen — APPROVED** [review]
An excellent addition. Thanks!

**Comment by bfriesen** [comment]
Will get this published in the next hour or two.

**Comment by bfriesen** [comment]
This is published: [RockLib.Messaging.SQS version 2.2.6](https://www.nuget.org/packages/RockLib.Messaging.SQS).

**Pull request merged**
